### ISSUE TITLE
Moment object is stored in dynamodb

### ISSUE THREAD

**Issue by faizshukri** [trek10inc/dynamodb-autoscaling#3]
I'm not sure if this happened to anyone, but it happened to me. Below is my finding on this issue.

First, when I create new record, moment object of `upDuration` and `downDuration` is being stored in dynamodb as well. Is this intended?

Secondly, even though they are being stored in dynamodb, I guess you want to ignore it by defining `upDuration` and `downDuration` getters.

```js
const DEFAULTS = {
  get upDuration() {
    return timeSpanToDuration(this.upTimeSpan);
  },

  get downDuration() {
    return timeSpanToDuration(this.downTimeSpan);
  }
}
```

However in `AutoScaleConfig`, the properties of `DEFAULTS` being copied using `Object.assign` (which is unsuitable to be use for merging if the sources contain getters, [source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Description))

```js
class AutoScaleConfig {
  constructor(rawData) {
    Object.assign(this, DEFAULTS, rawData); // <-- upDuration in rawData override upDuration in DEFAULTS
  }
}
```

And since `rawData` is just a plain object from DynamoDb, this line of code is not working anymore.

```js
scaleTable(config, direction) {
    this.logger.log('Getting table schema:', config.tableName);
    const analyzeDuration = config[direction + 'Duration']; // <-- This is not moment object anymore, instead just a plain object from dynamoDB
    const shared = {};
```

My quick fix was to remove both of them before saving into DynamoDb. But maybe there's a better solution for this.

Thanks,

Regards,
Faiz

**Comment by david-nadaraia** [comment]
RESOLVED
